point_filter_num : 4
max_iteration : 10
filter_size_surf : 0.5 # 0.3
filter_size_map : 0.5 # 0.4
cube_side_length : 1000 
img_enable : 1
reprojection_cov: 10
associated_lidar_num: 5  #lidar frame used to provide depth
frame_winsize: 8            #frame window size used to optimize
laser_point_cov : 0.001
delta_time: 0.0

common:
    lid_topic:  "/hesai/pandar"
    imu_topic:  "/alphasense/imu"

preprocess:
    lidar_type: 4  # Ouster
    scan_line: 32
    blind: 0.01 # blind x m disable

mapping:
    acc_cov: 0.001 #10
    gyr_cov: 0.001 #10
    extrinsic_T: [ -0.001, -0.00855, 0.055]
    extrinsic_R: [ 0,-1 , 0,
                   -1, 0, 0,
                   0, 0, -1]

camera:
    img_topic:  /alphasense/cam0/image_raw
    horizontal_fov: 126 #degree
    vertical_fov: 92.4 #degree
    # NTU_VIRAL
    Rcl: [-0.999926420062118,-0.00670802145180044,0.0101072701536599,
          -0.0100911970216883,-0.00242564364180353,-0.999946140547376,
           0.00673217679702115,-0.999974559026941,0.00235777319699915]
    Pcl: [-0.0549762046649811,0.0675401455352659,-0.0520599209018660]

model_path: "/home/sjz/Desktop/livo_ws/src/livo_fast/models"

gt_arm: [0.0, 0.0, 0.0]
